version: '3.8'

services:
  demo-app:
    build:
      context: consumer
      dockerfile: consumer/Dockerfile
    container_name: demo-app
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://timescaledb:5432/sensor-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-bitnami-kraft:9092
    depends_on:
      timescaledb:
        condition: service_healthy
    networks:
      - kafka-network
      - internal-network

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sensor-db
    ports:
      - "8085:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internal-network
      - kafka-network

networks:
  kafka-network:
    external: true

  internal-network:
    external: true
